{% set name = "perl-image-exiftool" %}
{% set version = "11.70" %}
{% set sha256 = "d745724ea3a4340d44b131351783b0bbe2b4f9d6d9d2707f4b9508f5f6071afc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-11.70.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  
requirements:
  host:
    - perl
    - perl-extutils-makemaker

  run:
    - perl

test:
  imports:
    - Image::ExifTool

  commands:
    - exiftool -ver

about:
  home: http://metacpan.org/pod/Image::ExifTool
  license: perl_5
  summary: 'ExifTool is a platform-independent Perl library plus a command-line application for reading, writing and editing meta information in a wide variety of files.'
