package:
  name: perl-getopt-long-subcommand
  version: "0.103"

source:
  url: https://cpan.metacpan.org/authors/id/P/PE/PERLANCAR/Getopt-Long-Subcommand-0.103.tar.gz
  md5: 64c070153cf372e403c9071b9b0eec50

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-getopt-long

  run:
    - perl
    - perl-getopt-long

test:
  imports:
    - Getopt::Long::Subcommand

about:
  home: https://metacpan.org/pod/Getopt::Long::Subcommand
  license: perl_5
  summary: 'Process command-line options, with subcommands and completion'
