{% set name = "duphold" %}
{% set version = "0.1.5" %}
{% set download_version = "0.1.15" %}  # tarball has been versioned incorrectly
{% set sha256hash = "f12f263a841ad5a2da9c00be564e4459c66155f0546e67e8114f0e7a8becfe4f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/brentp/duphold/releases/download/v{{ download_version }}/duphold_static
  sha256: {{ sha256hash }}

build:
  number: 0
  skip: True  # [osx]

test:
  commands:
    - duphold -h

about:
  home: https://github.com/brentp/duphold
  license: MIT
  summary: SV callers like lumpy look at split-reads and pair distances to find structural variants. This tool is a fast way to add depth information to those calls.

extra:
  skip-lints:
    #Packages a prebuilt binary
    - should_be_noarch_generic
