{% set name = "planemo" %}
{% set version = "0.62.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c8f7a8224ba669a5304d11522153f554f9b5d341d3df458942514bce16b7a74

build:
  number: 0
  noarch: python
  entry_points:
    - planemo=planemo.cli:planemo
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - aenum
    - bioblend >=0.10.0
    - click
    - docutils
    - ephemeris
    - galaxy-lib >=18.9.2
    - glob2
    - gxformat2 >=0.8.0
    - jinja2
    - lxml  # for planemo lint
    - oyaml
    - pyaml
    - python
    - pyyaml
    - six >=1.7.0
    - virtualenv

test:
  imports:
    - planemo
    - planemo.bioconda_scripts
    - planemo.commands
    - planemo.conda_verify
    - planemo.cwl
    - planemo.cwl.cwl2script
    - planemo.database
    - planemo.engine
    - planemo.galaxy
    - planemo.galaxy.test
    - planemo.linters
    - planemo.reports
    - planemo.shed
    - planemo.shed2tap
    - planemo.test
    - planemo.training
    - planemo.xml

  commands:
    - planemo --help

about:
  home: https://github.com/galaxyproject/planemo
  license: Academic Free License (AFL)
  summary: 'Command-line utilities to assist in building tools for the Galaxy project (http://galaxyproject.org/).'
  license_family: Apache

extra:
  container:
    # click requires a Unicode locale
    extended-base: True
