{% set name = "perl-www-mechanize" %}
{% set version = "1.94" %}
{% set sha256 = "c850571551276aad468a5ea2b3857310107671d943fc1c0b7cae3adf552c1002" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/WWW-Mechanize-1.94.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-http-server-simple
    - perl-module-build
    - perl-html-form
    - perl-cgi
    - perl-extutils-makemaker
    - perl-test-deep
    - perl-test-fatal
    - perl-test-output
    - perl-test-warnings
    - perl-test-memory-cycle
    - perl-encode-locale
    - perl-html-tree
    - perl-libwww-perl

  run:
    - perl
    - perl-http-server-simple
    - perl-html-form
    - perl-cgi
    - perl-encode-locale
    - perl-module-build
    - perl-html-tree
    - perl-libwww-perl

test:
  # Perl 'use' tests
  imports:
    - WWW::Mechanize
    
about:
  home: https://metacpan.org/pod/WWW::Mechanize
  license: perl_5
  summary: Handy web browsing in a Perl object
